# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\gui\MainWindow.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(296, 215)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.btnSearchSerialPort = QtWidgets.QPushButton(self.centralwidget)
        self.btnSearchSerialPort.setGeometry(QtCore.QRect(170, 10, 81, 31))
        self.btnSearchSerialPort.setObjectName("btnSearchSerialPort")
        self.comboPort = QtWidgets.QComboBox(self.centralwidget)
        self.comboPort.setGeometry(QtCore.QRect(30, 10, 111, 22))
        self.comboPort.setObjectName("comboPort")
        self.btnTestComm = QtWidgets.QPushButton(self.centralwidget)
        self.btnTestComm.setGeometry(QtCore.QRect(30, 50, 221, 31))
        self.btnTestComm.setObjectName("btnTestComm")
        self.btnStartComm = QtWidgets.QPushButton(self.centralwidget)
        self.btnStartComm.setGeometry(QtCore.QRect(30, 90, 221, 31))
        self.btnStartComm.setObjectName("btnStartComm")
        self.btnStopComm = QtWidgets.QPushButton(self.centralwidget)
        self.btnStopComm.setGeometry(QtCore.QRect(30, 130, 221, 31))
        self.btnStopComm.setObjectName("btnStopComm")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 296, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Collaudo Leonardo L24"))
        self.btnSearchSerialPort.setText(_translate("MainWindow", "Search Port"))
        self.btnTestComm.setText(_translate("MainWindow", "Test Comm"))
        self.btnStartComm.setText(_translate("MainWindow", "Start Comm"))
        self.btnStopComm.setText(_translate("MainWindow", "Stop Comm"))
